[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
board_build.mcu = esp32s3
board_build.psram = enabled
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
    bblanchon/ArduinoJson @ ^7.0.4
